name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  nextjs-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: 16.14
      - run: npm ci
      - run: npm run build

      - name: Execute tests (Unit and Feature tests) via Jest
        run: npm run test-ci